# Generated by Django 3.0.4 on 2020-03-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200330_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
